#!/bin/bash

############################################################################
#   (this script combines all rows from all BirdNET-Analyzer results-files # 
#	into a single file)  												   #
############################################################################

################################################################
# Initialize paths and variables - provided via command line   #
################################################################

# Check for required arguments
if [ "$#" -ne 2 ]; then
  echo
  echo "Missing arguments.  Expected paths for input_dir and output_file"
  exit 1
  echo
fi

# Input Directory:
# BirdNET output directory (containing all the files generated by BirdNET runs during the year)
# This parameter is set in the calling script.

input_dir="$1" 

# Output file:
# A single file which combines all the individual IDs found in the BirdNEt run-files 
# output_file="/Users/mikeoconnor/Documents/BirdWorkbench/birdnet_analyzer_run_files_COMBINED/run_files_COMBINED_2025.txt"

output_file="$2"

echo "success:"
echo "Input Directory: $input_dir"
echo "Output File: $output_file"

# Halt test run

# exit 1

################################################################
# Main script												   #
################################################################

# Ensure the output file is empty prior to being regenerated
> "$output_file"

# Variable to track if the header line has been written to the output file (supplied by the first file read)
# Note: all BirdOMatic programs presume that all BirdNET output files have the same data structure.  
# Rerun all years from the top to bring in the data with the same structure if that changes in any year.

header_written=false

# Loop through each file in the directory
for file in "$input_dir"/*; do

  # Skip files containing "analysis_params" in the filename
  if [[ "$file" == *analysis_params* ]]; then
    continue
  fi
  
  # Read each line in the file
  while IFS= read -r line || [[ -n "$line" ]]; do
    # Skip blank lines
    if [[ -z "$line" ]]; then
      continue
    fi
    
    # Check if line contains "Confidence"
    if [[ "$line" == *"Confidence"* ]]; then
      # Only write the header line once
      if [[ "$header_written" == false ]]; then
        echo "$line" >> "$output_file"
        header_written=true
      fi
    else
      # Append non-header line to output file
      echo "$line" >> "$output_file"
	  
    fi
  done < "$file"

 
done